// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates draft email responses for HR admins.
 *
 * - generateDraftEmailResponses - A function that generates draft email responses.
 * - GenerateDraftEmailResponsesInput - The input type for the generateDraftEmailResponses function.
 * - GenerateDraftEmailResponsesOutput - The return type for the generateDraftEmailResponses function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDraftEmailResponsesInputSchema = z.object({
  query: z.string().describe('The employee inquiry or request.'),
});

export type GenerateDraftEmailResponsesInput = z.infer<typeof GenerateDraftEmailResponsesInputSchema>;

const GenerateDraftEmailResponsesOutputSchema = z.object({
  draftResponses: z.array(z.string()).describe('An array of draft email responses.'),
});

export type GenerateDraftEmailResponsesOutput = z.infer<typeof GenerateDraftEmailResponsesOutputSchema>;

export async function generateDraftEmailResponses(input: GenerateDraftEmailResponsesInput): Promise<GenerateDraftEmailResponsesOutput> {
  return generateDraftEmailResponsesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDraftEmailResponsesPrompt',
  input: {schema: GenerateDraftEmailResponsesInputSchema},
  output: {schema: GenerateDraftEmailResponsesOutputSchema},
  prompt: `You are an HR assistant tasked with drafting email responses for employee inquiries. Generate multiple distinct draft email responses for the following query.  Each response should be professional and ready for review by an HR admin.

Query: {{{query}}}

Format your response as a JSON array of strings.  The 'draftResponses' field in the JSON should contain the responses.
`,
});

const generateDraftEmailResponsesFlow = ai.defineFlow(
  {
    name: 'generateDraftEmailResponsesFlow',
    inputSchema: GenerateDraftEmailResponsesInputSchema,
    outputSchema: GenerateDraftEmailResponsesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
