
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates draft email responses (subject and body) for HR admins.
 *
 * - generateDraftEmailResponses - A function that generates draft email responses.
 * - GenerateDraftEmailResponsesInput - The input type for the generateDraftEmailResponses function.
 * - GenerateDraftEmailResponsesOutput - The return type for the generateDraftEmailResponses function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDraftEmailResponsesInputSchema = z.object({
  query: z.string().describe('The employee inquiry or request, or a prompt for a new email.'),
});

export type GenerateDraftEmailResponsesInput = z.infer<typeof GenerateDraftEmailResponsesInputSchema>;

const DraftEmailSchema = z.object({
  subject: z.string().describe('A concise and relevant subject line for the email.'),
  body: z.string().describe('The full body content of the email draft.'),
});

const GenerateDraftEmailResponsesOutputSchema = z.object({
  drafts: z.array(DraftEmailSchema).describe('An array of draft emails, each with a subject and body.'),
});

export type GenerateDraftEmailResponsesOutput = z.infer<typeof GenerateDraftEmailResponsesOutputSchema>;

export async function generateDraftEmailResponses(input: GenerateDraftEmailResponsesInput): Promise<GenerateDraftEmailResponsesOutput> {
  return generateDraftEmailResponsesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDraftEmailResponsesPrompt',
  input: {schema: GenerateDraftEmailResponsesInputSchema},
  output: {schema: GenerateDraftEmailResponsesOutputSchema},
  prompt: `You are an HR assistant tasked with drafting emails. Generate multiple distinct draft email options based on the following query/prompt. For each option, provide both a relevant subject line and the full email body.

Query/Prompt: {{{query}}}

Format your response as a JSON object. The 'drafts' field in the JSON should contain an array of objects, where each object has a 'subject' (string) and a 'body' (string) field.
`,
});

const generateDraftEmailResponsesFlow = ai.defineFlow(
  {
    name: 'generateDraftEmailResponsesFlow',
    inputSchema: GenerateDraftEmailResponsesInputSchema,
    outputSchema: GenerateDraftEmailResponsesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
