apiVersion: v1
kind: Secret
metadata:
  name: hr-streamline-ai-secrets
type: Opaque
data:
  # Base64 encode your secrets before adding them here
  # Example: echo -n 'your_mongodb_connection_string' | base64
  MONGODB_URI: "eW91cl9tb25nb2RiX2Nvbm5lY3Rpb25fc3RyaW5n"
  JWT_SECRET: "eW91cl9zdHJvbmdfand0X3NlY3JldF9rZXk="
  ENCRYPTION_KEY: "eW91cl8zMl9ieXRlX2Jhc2U2NF9lbmNvZGVkX2VuY3J5cHRpb25fa2V5"
  GOOGLE_API_KEY: "eW91cl9nb29nbGVfYWlfYXBpX2tleQ=="
  NEXT_PUBLIC_BASE_URL: "aHR0cDovL2xvY2FsaG9zdDo5MDAy" # Update with your actual URL
  GOOGLE_CLIENT_ID: "eW91cl9nb29nbGVfY2xpZW50X2lk"
  GOOGLE_CLIENT_SECRET: "eW91cl9nb29nbGVfY2xpZW50X3NlY3JldA=="
  BREVO_API_KEY: "eW91cl9icmV2b19hcGlfa2V5"
