
// This file is NOT 'use server'
import {z} from 'genkit';

export const CopilotChatInputSchemaDef = z.object({
  userInput: z.string().describe('The message sent by the user to the copilot.'),
});

export const CopilotChatOutputSchemaDef = z.object({
  aiResponse: z.string().describe('The response generated by the AI copilot.'),
});
